import torch
import torch.optim as optim
from core.quantum_engine import QuantumSimulator

class QuantumGANTrainer:
    """
    Orchestrates the adversarial training of the Quantum Calibration GAN.
    Integrates the Physics Engine into the loss loop.
    """
    def __init__(self, generator, discriminator, device='cpu'):
        self.gen = generator.to(device)
        self.disc = discriminator.to(device)
        self.device = device
        self.sim = QuantumSimulator()
        
        self.optimizer_G = optim.Adam(self.gen.parameters(), lr=0.0002, betas=(0.5, 0.999))
        self.optimizer_D = optim.Adam(self.disc.parameters(), lr=0.0002, betas=(0.5, 0.999))
        self.criterion = torch.nn.BCEWithLogitsLoss()

    def physics_loss(self, generated_pulses, target_states):
        """
        Custom loss that penalizes pulses that violate quantum fidelity.
        This provides a 'Physics-Informed' gradient to the Generator.
        """
        # Note: In a real implementation, we'd use a differentiable 
        # simulator or a surrogate model to backprop through the physics.
        # For now, we simulate the 'target' feedback.
        return 0.0 # Placeholder for differentiable fidelity

    def train_step(self, real_pulses, z_noise):
        batch_size = real_pulses.size(0)
        
        # --- Train Discriminator ---
        self.optimizer_D.zero_grad()
        
        # Real pulses (perfectly calibrated samples)
        d_output_real = self.disc(real_pulses)
        label_real = torch.ones(batch_size, 1).to(self.device)
        loss_real = self.criterion(d_output_real, label_real)
        
        # Fake pulses (generated by GAN)
        fake_pulses = self.gen(z_noise)
        d_output_fake = self.disc(fake_pulses.detach())
        label_fake = torch.zeros(batch_size, 1).to(self.device)
        loss_fake = self.criterion(d_output_fake, label_fake)
        
        d_loss = (loss_real + loss_fake) / 2
        d_loss.backward()
        self.optimizer_D.step()

        # --- Train Generator ---
        self.optimizer_G.zero_grad()
        
        # We want Discriminator to think fake pulses are real
        g_output = self.disc(fake_pulses)
        g_loss = self.criterion(g_output, label_real)
        
        g_loss.backward()
        self.optimizer_G.step()
        
        return d_loss.item(), g_loss.item()
