import matplotlib.pyplot as plt
import numpy as np

def plot_pulse_sequence(pulses, title="Optimized Pulse Sequence"):
    """
    Visualizes I/Q pulse components generated by the GAN.
    """
    # pulses: [2, length]
    length = pulses.shape[1]
    time = np.linspace(0, 1, length)
    
    plt.figure(figsize=(10, 4))
    plt.plot(time, pulses[0], label='In-phase (I)', color='#ff5555', linewidth=2)
    plt.plot(time, pulses[1], label='Quadrature (Q)', color='#5555ff', linewidth=2)
    plt.fill_between(time, pulses[0], alpha=0.1, color='#ff5555')
    plt.fill_between(time, pulses[1], alpha=0.1, color='#5555ff')
    
    plt.title(title, fontsize=14, fontweight='bold')
    plt.xlabel("Normalized Time", fontsize=12)
    plt.ylabel("Normalized Amplitude", fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

def plot_bloch_trajectory(states):
    """Placeholder for 3D Bloch Sphere visualization."""
    pass
